name: Admin Escalation Demotion Workflow

on:
  issues:
    types: [closed]

jobs:
  demote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Obtain App Token
        uses: philips-software/app-token-action@v1.1.2
        id: token
        with:
          app_id: ${{ vars.APP_ID }}
          app_base64_private_key: ${{ secrets.APP_PRIVATE_KEY_BASE64 }}
          auth_type: installation

      - name: Parse Issue for Target Org
        id: parse
        uses: 040code/admin-support-issueops-actions/admin-support-cli@v1.0.0
        with:
          action: "parse_issue"
          issue_number: ${{ github.event.issue.number }}

      - name: Demote User to Member
        id: demote
        uses: 040code/admin-support-issueops-actions/admin-support-cli@v1.0.0
        with:
          action: "promote_demote"
          username: ${{ github.event.issue.user.login }}
          target_org: ${{ steps.parse.outputs.target_org }}
          role: "member"
          admin_token: ${{ steps.token.outputs.token }}

      - name: Comment on Demotion Success
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🔒 Admin access has been revoked from @${{ github.event.issue.user.login }}."
            })
