name: Configure Branch Protection Rulesets (Management Repo)

on:
  push:
    # Run if any .json file is modified or created/removed:
    paths:
      - ".github/workflows/branch-rulesets/**/*.json"
      - ".github/workflows/org-rulesets.yml"
  schedule:
    - cron: "0 6 * * *" # Run at 6 AM daily
  workflow_dispatch:

permissions: read-all

jobs:
  configure_rulesets_across_repos:
    runs-on: ubuntu-latest

    steps:
      - name: Convert App token (GitHub App with repo admin perms)
        id: create_token
        uses: getsentry/action-github-app-token@v3.0.0
        with:
          app_id: ${{ vars.FSDH_REPO_ADMIN_APP_ID }}
          private_key: ${{ secrets.FSDH_REPO_ADMIN_APP_KEY }}

      - name: Checkout management repo
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        run: |
          echo "[Stage] Setting up GitHub CLI"
          gh auth login --with-token <<< "${{ steps.create_token.outputs.token }}"

      - name: Configure rulesets in target repos
        env:
          GH_TOKEN: ${{ steps.create_token.outputs.token }}
        run: |
          echo "[Stage] Starting configuration of rulesets across repositories."

          # For each directory inside .github/workflows/branch-rulesets, treat
          # that directory name as the target repository name.
          for repo_dir in .github/workflows/branch-rulesets/*; do
            if [ -d "$repo_dir" ]; then
              repo_name="$(basename "$repo_dir")"
              echo "\n=== [Processing Repository] $repo_name ==="

              # Collect ruleset names from local JSON files
              local_ruleset_names=()
              echo "[Info] Collecting local ruleset files for $repo_name."
              for ruleset_file in "$repo_dir"/*.json; do
                [ -f "$ruleset_file" ] || continue
                # We'll treat the file name (minus .json) as the ruleset name
                ruleset_name="$(basename "$ruleset_file" .json)"
                local_ruleset_names+=("$ruleset_name")
                echo "[Found Ruleset] $ruleset_name from file $ruleset_file."
              done

              echo "[Summary] Local rulesets for $repo_name: ${local_ruleset_names[*]}"

              # List existing rulesets on the *target* repo
              echo "[Info] Fetching existing rulesets from GitHub for $repo_name."
              existing_ruleset_names="$(gh api "repos/${{ github.repository_owner }}/$repo_name/rulesets" --jq '.[].name' 2>/dev/null || true)"